from datetime import datetime, timezone
from pydantic import BaseModel, Field


class SlideOutline(BaseModel):
    """Content for a single slide in the presentation."""

    title: str
    subtitle: str | None = None
    bullets: list[str] = Field(default_factory=list)
    layout_type: str = "content"  # title | section | content | two_column | ending


class PresentationOutline(BaseModel):
    """Complete presentation outline generated by the LLM."""

    topic: str
    slides: list[SlideOutline] = Field(default_factory=list)
    style_notes: str | None = None


class TodoItem(BaseModel):
    """A single step in the execution plan."""

    id: int
    description: str
    tools_needed: list[str] = Field(default_factory=list)
    depends_on: list[int] = Field(default_factory=list)
    status: str = "pending"  # pending | in_progress | completed | blocked


class Plan(BaseModel):
    """Execution plan: breaks down the user request into ordered steps."""

    goal: str
    items: list[TodoItem] = Field(default_factory=list)
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    revised_at: str | None = None
